defaults: &defaults
  adapter: postgresql
  template: template0

production:
  <<: *defaults
  database: travelmemories_production
  user: travelmemories
  password: 123QWEasdZXC

development:
  <<: *defaults
  database: travelmemories_development

test:
  <<: *defaults
  min_messages: warning #magic sauce
  database: travelmemories_test