development:
  token: "ONE0Y4MGCCUHYLX512YJ1Z2DXUCF4HN0BYFE2C5BQ5UTLJ2W"
  secret: "2PR5P20A3MVXQ2P0RTR2BCENV00LJZFGKKMVYZKE5JKXMXTN"

production:
  token: "2VLIEXZNO3LYBDSJXA0WP5OUDVTL3NN31OOIHGA2BQOJAYI4"
  secret: "PP53OYYXVX5X1VRJDQM3GE0FIKXQSHDJRH1GFFANXDUVBYKE"
